name: Deploy Wandu Backend

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드 체크아웃
      - name: 체크아웃
        uses: actions/checkout@v3

      # 2. JDK 17 설정
      - name: JDK 17 사용
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      # 3. application.properties 생성
      - name: Create application.properties
        run: |
          touch ./src/main/resources/application.properties
          echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.properties
          cat ./src/main/resources/application.properties

      # 4. Gradle 실행 권한
      - name: Gradle Wrapper 실행 권한 추가
        run: chmod +x gradlew

      # 5. 빌드
      - name: Gradle로 빌드(CI)
        run: ./gradlew build

      # 6. DockerHub 로그인
      - name: 도커허브에 로그인
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 빌드 산출물 확인
      - name: 빌드 산출물 확인
        run: ls -lh ./build/libs

      # 7. 이미지 빌드
      - name: 이미지 빌드
        run: |
          cp ./wand-backend/build/libs/wandu-backend-0.0.1-SNAPSHOT.jar ./app.jar
          docker build -t ${{ secrets.DOCKER_USERNAME }}/wandu-backend .

      # 8. DockerHub에 푸시
      - name: 도커허브에 이미지 푸시
        run: docker push ${{ secrets.DOCKER_USERNAME }}/wandu-backend

      # 9. EC2 SSH 접속 후 배포
      - name: AWS EC2에 ssh 접속 후 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PROD }}
          port: 22
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            APP_DIR=/home/ubuntu/wandu-backend
            echo "AWS 연결"

            # Git clone 또는 pull
            if [ ! -d "$APP_DIR/.git" ]; then
              # 기존 소스 초기화
              sudo rm -rf $APP_DIR
              sudo mkdir -p $APP_DIR

              echo "Git 저장소 없음 → 클론 실행"
              sudo git clone https://github.com/wandu-k/wandu-backend.git .
            else
              echo "Git 저장소 있음 → 최신으로 pull"
              cd $APP_DIR
              sudo git reset --hard
              sudo git clean -fd
              sudo git pull origin main
            fi
          
            sudo docker stop wandu-backend || true
            sudo docker rm wandu-backend || true

            # 최신 이미지 가져오기
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/wandu-backend

            # 컨테이너 실행
            sudo docker run -d \
              --name wandu-backend \
              -p 8082:8082 \
              -e SPRING_PROFILES_ACTIVE=prod \
              ${{ secrets.DOCKER_USERNAME }}/wandu-backend
